/// <reference types="@cloudflare/workers-types" />

/**
 * @module deployer
 *
 * Deploy orchestration for A3lix.
 *
 * - `deployPreview()` creates a preview branch + commit in GitHub.
 * - `approveAndMerge()` merges an approved preview branch to the base branch.
 */

import type { GitHubConfig, GitHubFileChange } from './github';
import { createPreviewBranch, mergeToMain } from './github';

export interface DeployConfig {
  pagesProjectName: string;
  framework: 'astro' | 'nextjs';
}

export interface DeployResult {
  branchName: string;
  previewUrl: string;
  commitSha: string;
  deployedAt: string;
  estimatedBuildSeconds: number;
  previewReady: boolean;
}

export async function deployPreview(params: {
  githubConfig: GitHubConfig;
  deployConfig: DeployConfig;
  userId: string;
  changes: GitHubFileChange[];
  summary: string;
}): Promise<DeployResult> {
  const { githubConfig, deployConfig, userId, changes, summary } = params;

  const commitMessage =
    `feat: A3lix preview — ${summary}\n\nRequested by user ${userId}\nGenerated by A3lix Bot`;

  const result = await createPreviewBranch({
    config: githubConfig,
    userId,
    changes,
    commitMessage,
    pagesProjectName: deployConfig.pagesProjectName,
  });

  const estimatedBuildSeconds = deployConfig.framework === 'astro' ? 45 : 60;

  return {
    branchName: result.branchName,
    previewUrl: result.previewUrl,
    commitSha: result.commitSha,
    deployedAt: new Date().toISOString(),
    estimatedBuildSeconds,
    previewReady: false,
  };
}

export async function approveAndMerge(params: {
  githubConfig: GitHubConfig;
  branchName: string;
  summary: string;
  userId: string;
}): Promise<{ commitSha: string }> {
  const { githubConfig, branchName, summary, userId } = params;

  const commitMessage =
    `feat: A3lix approved — ${summary}\n\nApproved by owner ${userId}\nMerged by A3lix Bot`;

  const result = await mergeToMain(githubConfig, branchName, commitMessage);

  if (!result.merged) {
    throw new Error(
      `Merge of branch "${branchName}" was a no-op — no new commits to merge.`,
    );
  }

  return { commitSha: result.commitSha };
}
